armies:
  - factory:
      type: :dummy
      name: "Dummy Trooper 1"
      sleep_duration: 10
    max_threads: 2
    name: "Dad's Army"
  - factory: 
      type: :dummy
      name: "Dummy Trooper 2"
      sleep_duration: 5
    max_threads: 2
